services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    volumes:
      - ./backend:/app
      - /app/node_modules

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eddys-tender-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
