services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - NODE_ENV=development
      - TZ=America/Hermosillo
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mysql:
    image: mysql:8.0
    platform: linux/amd64 # Asegura compatibilidad multiplataforma
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: eddys-tender-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
      TZ: America/Hermosillo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
      - ./mysql/conf:/etc/mysql/conf.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puser_password"]
      interval: 10s
      timeout: 5s
      retries: 5
  stripe-cli:
    image: stripe/stripe-cli
    container_name: stripe-cli
    command: listen --forward-to http://backend:3000/api/webhooks/stripe --api-key=${STRIPE_SECRET_KEY}
    env_file:
      - ./backend/.env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data:
    name: eddys-tender-app_mysql_data
